apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: dmitiriy/nginx-rep-task4:latest
          ports:
            - containerPort: 80

---


apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    env: dep
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - name: nginx-listener
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000